apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: machine-config-operator
  labels:
    change-build-arg-tags: "true"
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/machine-config-operator'
      ref: release-4.12
    contextDir: .
    images: []
  strategy:
    type: Docker
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      dockerfilePath: Dockerfile
      buildArgs:
        - name: "TAGS"
          value: "okd"
      from:
        kind: "ImageStreamTag"
        name: "release:base"
  output:
    to:
      kind: ImageStreamTag
      name: 'release:machine-config-operator'
