apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../buildconfigs
  - ../../pipelines

patches:
  - patch: |-
      - op: add
        path: /spec/strategy/dockerStrategy/dockerfilePath
        value: Dockerfile.scos
    target:
      kind: BuildConfig
      name: ironic
  - patch: |-
      apiVersion: build.openshift.io/v1
      kind: BuildConfig
      metadata:
        name: not-used
        labels:
          change-build-arg-tags: ""
      spec:
        strategy:
          dockerStrategy:
            buildArgs:
              - name: "TAGS"
                value: "scos"
    target:
      labelSelector: "change-build-arg-tags==true"
      kind: BuildConfig
  - patch: |-
      - op: add
        path: "/spec/tags/-"
        value:
          name: centos-stream-coreos-9
          from:
            kind: DockerImage
            name: quay.io/okd/centos-stream-coreos-9:4.12-x86_64
          referencePolicy:
            type: Local
          importPolicy:
            scheduled: true
            importMode: PreserveOriginal # Needs OKD 4.13
    target:
      kind: ImageStream
      name: release
  - patch: |-
      - op: add
        path: "/spec/tags/-"
        value:
          name: machine-os-content
          from:
            kind: ImageStreamTag
            name: release:centos-stream-coreos-9
          referencePolicy:
            type: Local
          importPolicy:
            importMode: PreserveOriginal # Needs OKD 4.13 (and an actual manifest list scos image to import)
    target:
      kind: ImageStream
      name: release
# TODO: handling multi-arch images for the OSes.
